version: "3"

services:
    micro:
          container_name: microMoviles
          restart: always
          build: .
          ports: 
              - "5000:5000"
          links:
              - mongo    
    
    mongo: 
          container_name: mongodb
          image: mongo
          ports: 
              - "27017:27017"
